include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-hotplug

LUCI_TITLE:=LuCI interface for hotplug configuration
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all
PKG_VERSION:=1.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
