include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-powersupply

LUCI_TITLE:=LT70 power supply control utility
LUCI_DEPENDS:=+luci-base
LUCI_DEPENDS:=powersupply
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
