#pragma once
enum eProcessorType { PXA_NONE = -1,
	PXA168 = 0, 
	PXA30x, PXA31x, PXA32x, 
	PXA688,
	PXA91x, PXA92x, PXA93x, PXA94x, PXA95x, 
	ARMADA168,
	PXA2128,
	MG1,
	TAVOR_PV_MG2,
	ESHEL,
	PXA988,
	PXA1088,
	PXA1202,
	PXA1802,
	PXA1928,
	PXA1920,
	PXA1822,
	ARMADA620,
	ESHEL_LTE,
	ARMADA622,
	WUKONG,
	PXA1826,
	PXA1908,
	PXA1936,
	PXA1956,
	PXA1918,
	PXAMAX_PT 
};




typedef enum 
{
	BLF_V_3_0_0 = 0,
	BLF_V_2_0_0 = 1,
	UNKNOWN_VERSION = 0xFF

}eBLFVersion;

typedef enum 
{
	FLASH = 0,
	DDR,
	UNKNOWN_TYPE
}EUploadType;
typedef enum _eFlashType
{
	FLASH_NAND = 0,
	FLASH_EMMC = 1,
	FLASH_SPINOR = 2,
	FLASH_ONENAND = 3,
	FLASH_SPINAND = 4,
	FLASH_UNKNOWN = 10
}
eFlashType;

enum eEraseAllMode
{
	ERASE_ALL_NOTSET = 0,
	ERASE_ALL_BEFOREBURNING = 1,
	ERASE_ALL_WIHTOUTBURNING = 2,
	UNKNOWN_MODE = 0xFF

};

typedef enum  _eUserBootMode 
{
	UE_NORESET = 0,
	UE_RESET = 1,
	UNKNOWN_BOOT_MODE = 0xFF

}
eUserBootMode;
typedef enum
{
	PLAT_PXA92x_Old=0,
	PLAT_PXA92x ,
	PLAT_MMP2 ,
	PLAT_WUKONG,
	PLAT_NEVO,//
	PLAT_MMP3,
	PLAT_NEZHA,
	PLAT_NEVO_OTA,
	PLAT_EMEI,
	PLAT_HELAN,
	PLAT_EDEN, //PLAT_EDEN_Zx
	PLAT_HELANLTE,
	PLAT_NEZHA2,
	PLAT_HELAN2,
	PLAT_EDEN_A0,
	PLAT_NEZHA3,
	PLAT_ULC1,
	PLAT_HELAN3,
	PLAT_HELAN4,
	PLAT_ULC2,
	PLAT_UNKNOWN = 0xff
} ePlatForm;

//subtype enum for upload 
enum EUploadSubType
{
	DEFAULT_FLASH_PROBE = 0,
	HSI1,
	X16_ONENAND,
	XIP_FLASH_X16,
	X16_NAND_HAMMING,
	X16_XIP_SIBLEY,
	NAND_X8_HAMMING,
	SDMMC_FLASH_OPT0,
	SDMMC_FLASH_OPT1,
	SDMMC_FLASH_OPT2,
	SPI_FALSH,
	SDMMC_FLASH_OPT3,
	SDMMC_FLASH_OPT4,
	X16_NAND_BCH,
	X8_NAND_BCH,
	CS1_XIP_FLASH,            // XIP (CS1) - for SV only
	NAND_FLASH_X16_BCH_OPT1, // x16 NAND BCH (16 bit correction per 1K)
	NAND_FLASH_X8_BCH_OPT1, // x8 NAND BCH (16 bit correction per 1K)
	NAND_FLASH_X16_NO_ECC,// x16 NAND No ECC (ECC is done by flash device)
	NAND_FLASH_X8_NO_ECC, // x8 NAND No ECC (ECC is done by flash device)
	SDIO_BUS,
	BOOTSPI_FLASH, 
	SPI_NAND_FLASH = 26,
	UNKOWN_SUBTYPE = 0xff
};

enum eProductMode{
	DO_NOTHING_FUSE,
	ONLY_BURN_FUSE,
	ONLY_READ_FUSE,
	BURN_READ_FUSE,
	DONTBURN_ONLY_BURN_FUSE,
	DONTBURN_ONLY_READ_FUSE,
	DONTBURN_BURN_READ_FUSE,
};

enum eDDREMMCTypeMode{
	NoneType,
	DDRType,
	EMMCType,
	DDRandEMMCType,
};
