#pragma once

typedef enum
{
	TIMH_NOTINC = 0,
	TIMH_INC = 1,
	DTIM_PRIMARY = 2,
	DTIM_RECOVERY = 3,
	DTIM_CP = 4,
	TIMH_RECOVERYINC = 5,
	DTIM_PPINFO = 6,
	DTIM_CUSTMOZIEDTYPE1 = 10,
	DTIM_CUSTMOZIEDTYPE2 = 11,
	DTIM_CUSTMOZIEDTYPE3 = 12,
	DTIM_CUSTMOZIEDTYPE4 = 13,
	DTIM_CUSTMOZIEDTYPE5 = 14,
	DTIM_CUSTMOZIEDTYPE6 = 15,
	DTIM_CUSTMOZIEDTYPE7 = 16,
	DTIM_CUSTMOZIEDTYPE8 = 17,
	DTIM_CUSTMOZIEDTYPE9 = 18,
	DTIM_CUSTMOZIEDTYPE10 = 19,
	DTIM_CUSTMOZIEDTYPE11 = 20,
	DTIM_CUSTMOZIEDTYPE12 = 21,
	DTIM_CUSTMOZIEDTYPE13 = 22,
	DTIM_CUSTMOZIEDTYPE14 = 23,
	DTIM_CUSTMOZIEDTYPE15 = 24,
	DTIM_CUSTMOZIEDTYPE16 = 25,
	DTIM_CUSTMOZIEDTYPE17 = 26,
	DTIM_CUSTMOZIEDTYPE18 = 27,
	DTIM_CUSTMOZIEDTYPE19 = 28,
	DTIM_CUSTMOZIEDTYPE20 = 29,
	DKB_TIM				  = 100,
	FBF_TIM				  = 101,
	UNKOWN_TIMTYPE        = 0xFF
}
TIMINCLUDEDTYPE_T;