include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-snmpd-ssl

LUCI_TITLE:=Net-SNMP LuCI interface with v3 support
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
